# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/k3gxx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/bcm4350_V0301.0562.hcd:system/vendor/firmware/bcm4350_V0301.0562.hcd \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/bcm4350_V0301.0563_wisol.hcd:system/vendor/firmware/bcm4350_V0301.0563_wisol.hcd \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_2p2_master_setfile.bin:system/vendor/firmware/companion_2p2_master_setfile.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_2p2_mode_setfile.bin:system/vendor/firmware/companion_2p2_mode_setfile.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_default_coef.bin:system/vendor/firmware/companion_default_coef.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_default_lsc.bin:system/vendor/firmware/companion_default_lsc.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_fw_2p2_evt1.bin:system/vendor/firmware/companion_fw_2p2_evt1.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_fw_evt0.bin:system/vendor/firmware/companion_fw_evt0.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/fimc_is_fw2_2p2.bin:system/vendor/firmware/fimc_is_fw2_2p2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_2p2.bin:system/vendor/firmware/setfile_2p2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_8b1.bin:system/vendor/firmware/setfile_8b1.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp1-edac.bin:system/etc/firmware/florida-dsp1-edac.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp1-edac.wmfw:system/etc/firmware/florida-dsp1-edac.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp2-tx-nb.wmfw:system/etc/firmware/florida-dsp2-tx-nb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp2-tx-swb.wmfw:system/etc/firmware/florida-dsp2-tx-swb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp2-tx-wb.wmfw:system/etc/firmware/florida-dsp2-tx-wb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-ez2-control.wmfw:system/etc/firmware/florida-dsp3-ez2-control.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-lpsd-control.bin:system/etc/firmware/florida-dsp3-lpsd-control.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-nb.bin:system/etc/firmware/florida-dsp3-tx-nb.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-nb.wmfw:system/etc/firmware/florida-dsp3-tx-nb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-swb.wmfw:system/etc/firmware/florida-dsp3-tx-swb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-swb-conversation.bin:system/etc/firmware/florida-dsp3-tx-swb-conversation.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-swb-interview.bin:system/etc/firmware/florida-dsp3-tx-swb-interview.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-wb.bin:system/etc/firmware/florida-dsp3-tx-wb.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp3-tx-wb.wmfw:system/etc/firmware/florida-dsp3-tx-wb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.bin:system/etc/firmware/florida-dsp4-rx-anc-nb.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-nb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.bin:system/etc/firmware/florida-dsp4-rx-anc-wb.bin \
  vendor/samsung/k3gxx/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-wb.wmfw \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt_semco3rd:system/etc/wifi/nvram_mfg.txt_semco3rd \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt_wisol:system/etc/wifi/nvram_mfg.txt_wisol \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt_semco3rd:system/etc/wifi/nvram_net.txt_semco3rd \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt_wisol:system/etc/wifi/nvram_net.txt_wisol \
  vendor/samsung/k3gxx/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
  vendor/samsung/k3gxx/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
  vendor/samsung/k3gxx/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
  vendor/samsung/k3gxx/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
  vendor/samsung/k3gxx/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/libmysound.so:system/lib/libmysound.so \
  vendor/samsung/k3gxx/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
  vendor/samsung/k3gxx/proprietary/lib/soundfx/libaudiosa_sec.so:system/lib/soundfx/libaudiosa_sec.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/liblvverx_3.21.13.so:system/vendor/lib/liblvverx_3.21.13.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/liblvvetx_3.21.13.so:system/vendor/lib/liblvvetx_3.21.13.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/camera.universal5422.so:system/lib/hw/camera.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_bestface_T.so:system/lib/libarcsoft_magicshot_bestface_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_bestphoto_T.so:system/lib/libarcsoft_magicshot_bestphoto_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_common_T.so:system/lib/libarcsoft_magicshot_common_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_drama_T.so:system/lib/libarcsoft_magicshot_drama_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_eraser_T.so:system/lib/libarcsoft_magicshot_eraser_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_magicshot_picmotion_T.so:system/lib/libarcsoft_magicshot_picmotion_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_night_shot_ex.so:system/lib/libarcsoft_night_shot_ex.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_panorama_burstcapture.so:system/lib/libarcsoft_panorama_burstcapture.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_picaction.so:system/lib/libarcsoft_picaction.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_picmotion_T.so:system/lib/libarcsoft_picmotion_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_preprocessor_T.so:system/lib/libarcsoft_preprocessor_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_readengine_T.so:system/lib/libarcsoft_readengine_T.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_selfie_camera_lite.so:system/lib/libarcsoft_selfie_camera_lite.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_sensorndk.so:system/lib/libarcsoft_sensorndk.so \
  vendor/samsung/k3gxx/proprietary/lib/libarcsoft_vdoinvideo.so:system/lib/libarcsoft_vdoinvideo.so \
  vendor/samsung/k3gxx/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
  vendor/samsung/k3gxx/proprietary/lib/libvdis.so:system/lib/libvdis.so \
  vendor/samsung/k3gxx/proprietary/bin/drsd:system/bin/drsd \
  vendor/samsung/k3gxx/proprietary/bin/exyrngd:system/bin/exyrngd \
  vendor/samsung/k3gxx/proprietary/bin/gps.cer:system/bin/gps.cer \
  vendor/samsung/k3gxx/proprietary/bin/gpsd:system/bin/gpsd \
  vendor/samsung/k3gxx/proprietary/bin/npsmobex:system/bin/npsmobex \
  vendor/samsung/k3gxx/proprietary/bin/rild:system/bin/rild \
  vendor/samsung/k3gxx/proprietary/bin/sensorhubservice:system/bin/sensorhubservice \
  vendor/samsung/k3gxx/proprietary/bin/vcsFPService:system/bin/vcsFPService \
  vendor/samsung/k3gxx/proprietary/lib/hw/gps.universal5422.so:system/lib/hw/gps.universal5422.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/sensors.universal5422.so:system/lib/hw/sensors.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
  vendor/samsung/k3gxx/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
  vendor/samsung/k3gxx/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/samsung/k3gxx/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/samsung/k3gxx/proprietary/lib/librilutils.so:system/lib/librilutils.so \
  vendor/samsung/k3gxx/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
  vendor/samsung/k3gxx/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
  vendor/samsung/k3gxx/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000003.tlbin:system/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000007.tlbin:system/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000008.tlbin:system/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000011.tlbin:system/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
  vendor/samsung/k3gxx/proprietary/bin/scranton_RD:system/bin/scranton_RD \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libmalicore.bc:system/vendor/lib/libmalicore.bc \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libRSDriverArm.so:system/vendor/lib/libRSDriverArm.so \
  vendor/samsung/k3gxx/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
  vendor/samsung/k3gxx/proprietary/lib/libhr.so:system/lib/libhr.so \
  vendor/samsung/k3gxx/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
  vendor/samsung/k3gxx/proprietary/bin/lpm:system/bin/lpm \
  vendor/samsung/k3gxx/proprietary/lib/hw/power.exynos5.so:system/lib/hw/power.exynos5.so \
  vendor/samsung/k3gxx/proprietary/bin/olsrd:system/bin/olsrd \
  vendor/samsung/k3gxx/proprietary/bin/wlandutservice:system/bin/wlandutservice \
  vendor/samsung/k3gxx/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
  vendor/samsung/k3gxx/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
  vendor/samsung/k3gxx/proprietary/bin/samsungpowersoundplay:system/bin/samsungpowersoundplay \
  vendor/samsung/k3gxx/proprietary/bin/mfgloader:system/bin/mfgloader \
  vendor/samsung/k3gxx/proprietary/bin/connfwexe:system/bin/connfwexe \
  vendor/samsung/k3gxx/proprietary/bin/smdexe:system/bin/smdexe \
  vendor/samsung/k3gxx/proprietary/bin/ss_conn_daemon:system/bin/ss_conn_daemon \
  vendor/samsung/k3gxx/proprietary/bin/ss_kbservice_daemon:system/bin/ss_kbservice_daemon \
  vendor/samsung/k3gxx/proprietary/bin/tlc_server:system/bin/tlc_server \
  vendor/samsung/k3gxx/proprietary/lib/libAMSWiFiLibs-1.0.6.so:system/lib/libAMSWiFiLibs-1.0.6.so
